### ISSUE TITLE
nwis: be able to parse site parameter data when there are more than one data collection methods

### ISSUE THREAD

**Issue by solomon-negusse** [ulmo-dev/ulmo#119]
This broke a couple of reservoirs' data updates when USGS started using RADAR water level sensors in in place of pressure transducers but kept providing values from both methods with -999s for the original method.  Ulmo just returns the data from the first method. Here is an example:
http://waterservices.usgs.gov/nwis/iv/?format=waterml&sites=08054500&startDT=2015-12-16&endDT=2015-12-18&parameterCd=00062. 
So it looks like the code: https://github.com/ulmo-dev/ulmo/blob/master/ulmo/waterml/common.py#L8  is parsing just the first values element and ignoring the rest so we can modify this to loop through all. 
We can keep the existing dicts structure to store the data and encode the data collection method in the keys like  'variable:statistics_code:method' and store the method description in the data['parameter_code']['variable'] dict.
@dharhas @wilsaj  I'd  appreciate your thoughts on this.

**Comment by wilsaj** [comment]
Yikes. This is a pretty nasty bug.

Your fix seems to be the most correct thing to do but I'm concerned that it would be a huge breaking change for any code that relies on the existing key structure. We should also consider ways to ease that breakage (for example: by making it opt-in with a deprecation warning for some period of time).

Or as a non-breaking alternative: add an optional kwarg that allows filtering for a specific method (example: `method='RADAR'`). Could work like this:
- if `method=none` (default) 
  - if there is only one method, then it behaves as it currently does
  - if there is more than one method, then throw an error saying that the method needs to be specified and list available methods
- if `method` is a string (example: `method="RADAR"`), then it filter to that method
- there can be a special form that is something like `method='ANY'` where every available method is parsed and split out the 'variable:statistics_code:method' form

**Comment by solomon-negusse** [comment]
Thanks Andy! I'll go ahead with the non-breaking option you suggested. In my case it will make life easier when dealing with reservoir data later.

**Comment by dharhas** [comment]
+1 on Andy's non-breaking alternative.
