### ISSUE TITLE
Adding DAYMET single pixel time series from ORNL DAAC service 

### ISSUE THREAD

**Issue by ColinTalbert** [ulmo-dev/ulmo#126]
I've got some code that I've contributed to in a separate package which hits the DAAC Daymet time series service, and return it as a pandas dataframe.  See example here: https://github.com/ColinTalbert/daymetpy/blob/master/Examples/DaymetPy%20Demo.ipynb

It's a bit goofy in that that's the only function in the package.  Would you be interested in adding this dataset service to ulmo?  I could potentially submit a pull request on that if you'd like.

It was originally released under a GNU license, but in reality it's simple enough that rewriting it from scratch would be relatively easy if that was a major issue.

let me know what you think,

--Colin

**Comment by dharhas** [comment]
That would be a great addition. ulmo is BSD licensed so a rewrite/relicensing would be needed to include it. A pull request would be great.

Right now ulmo is a loose collection of useful packages without any enforcement of a common api. I've had plans to make the api consistent across data services but don't have the time. If you can try and use similar function calls and kwargs for things like start/end dates to the other existing data services that would help. Let me know if you have questions

**Comment by ColinTalbert** [comment]
Hello Dharhas,

I'm rewriting it to match the existing ulmo conventions (hopefully), which
will also make it good on the licensing.  Should be done shortly.

A quick question about the conventions in ulmo, The service returns a csv
file.  How do you handle where to save this to (how do I get a local
fname)?  Also do I need to include a check to see if the local file exists
before hitting the service?  If so is there a mechanism in place I should
use for this?

Thanks,
Colin

Colin Talbert
GIS Analyst and Developer
US Geological Survey

talbertc@usgs.gov

USGS Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425

USGS North Central Climate Science Center
(970) 492-4283

Work schedule:
Monday       - 7:00 - 3:00  (FORT)
Tuesday       -  7:00 - 3:00  (NC CSC)
Wednesday  -  7:00 - 3:00 (FORT)
Thursday      -  7:00 - 5:00 (FORT)
Friday          -  7:00 - 5:00 (FORT)

**Comment by dharhas** [comment]
The ulmo.util module has several useful functions for those purposes.

if you look at https://github.com/ulmo-dev/ulmo/blob/master/ulmo/ncdc/ghcn_daily/core.py

You'll see that we use a default ulmo dir + a sub directory. For the actual local filename, your module gets to pick something unique but consistent, you could use the name of the csv you are downloading or site_number.csv etc

GHCN_DAILY_DIR = os.path.join(util.get_ulmo_dir(), 'ncdc/ghcn_daily')

The path below is the full path with the filename.

util.download_if_new(url, path, check_modified=check_modified)

check_modified also checks the last modified date from the website if available.

**Comment by ColinTalbert** [comment]
I ended up following the model of the usgs/nwis module  which uses an open
file handler instead of a local filename.  So that nothing is written out
to the local filesystem, unless an user manually writes out the csv.  I've
pushed the Daymet code up to my github fork (
https://github.com/ColinTalbert/ulmo/tree/Add_DAYMET) if you get a chance
could you look it over to check that it's consistent enough with existing
ulmo conventions?

If it seems reasonable enough, I'll add a test or two and an example and
submit a pull request.

Thanks,
Colin

Colin Talbert
GIS Analyst and Developer
US Geological Survey

talbertc@usgs.gov

USGS Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425

USGS North Central Climate Science Center
(970) 492-4283

Work schedule:
Monday       - 7:00 - 3:00  (FORT)
Tuesday       -  7:00 - 3:00  (NC CSC)
Wednesday  -  7:00 - 3:00 (FORT)
Thursday      -  7:00 - 5:00 (FORT)
Friday          -  7:00 - 5:00 (FORT)

**Comment by dharhas** [comment]
Couple of comments.

1. Most of ulmo's module return either a Panda dataframe or a python dict, I'm not sure about returning an open file handle. Can you think of a good use case for that? Part of the point of ulmo is you've done the basic parsing.

2. Just a comment. pd.read_csv can read a url directly, but what you've done works just as well and has better error checking.

3. Please do add some add some tests and do a pull request.
