### ISSUE TITLE
empty list of features returned by ulmo.usgs.ned.get_raster_availability()

### ISSUE THREAD

**Issue by aleaf** [ulmo-dev/ulmo#132]
I'm guessing something is wrong with the way the url is being constructed?

Where did you find information on how to construct the url for Sciencebase? I have tried searching but can't find anything.

Thanks.

```python
In [1]:

import ulmo
ulmo.usgs.ned.get_raster_availability('1/3 arc-second', 
                                      (-89.5, 44.9, -88.05, 46.3))
```
retrieving raster availability from https://www.sciencebase.gov/catalog/items?fields=webLinks,spatial,title&q=&filter=tags=National Elevation Dataset (NED) 1/3 arc-second&filter=tags=IMG&filter=spatialQuery=Polygon ((-89.5 46.3,-89.5 44.9,-88.05 44.9,-88.05 46.3,-89.5 46.3))&format=json&max=1000
```python
Out[1]:
{"features": [], "type": "FeatureCollection"}
```

**Comment by dharhas** [comment]
sciencebase changed recently (about a week or two ago) and broke my query. There is a better way to get the list using parentId i.e.

https://www.sciencebase.gov/catalog/items?parentId=4f70ab22e4b058caae3f8deb&format=json&max=1000

so we need to change that. Its on my todo list but I'm not sure when I'll get to it. Pull requests welcome.

you can play around here to learn how to construct queries

https://www.sciencebase.gov/catalog/items/queryForm?parentId=4f70ab22e4b058caae3f8deb&&max=20

**Comment by dharhas** [comment]
Also for reference here is some code I used in an non public script for land cover:
```python
        base_url = 'https://www.sciencebase.gov/catalog/items'
        params = [
            ('filter', 'tags!=tree canopy'),
            ('filter', 'tags!=Imperviousness'),
            ('filter', 'tags=GeoTIFF'),
            ('max', 1000),
            ('fields', 'webLinks,spatial,title'),
            ('format', 'json')
        ]

        if service == '2001':
            params.append(('parentId', '4f70a45ee4b058caae3f8db9'))

        if service == '2006':
            params.append(('parentId', '4f70a46ae4b058caae3f8dbb'))

        if service == '2011':
            params.append(('parentId', '513624bae4b03b8ec4025c4d'))

        r = requests.get(base_url, params=params)
```

**Comment by aleaf** [comment]
Thanks!
This works (for now anyways):
```python
wkt = 'POLYGON ((-89 45,-89 46,-88 46,-88 45,-89 45))'
relation = 'intersects'
polygon_url = 'https://www.sciencebase.gov/catalog/items?filter=spatialQuery={{wkt:"%s",relation:"%s"}}\
&parentId=4f70ab22e4b058caae3f8deb&format=json&max=1000'.format(wkt, relation)
url = polygon_url %(wkt, relation)
url = url.replace(' ', '%20')
print(url)
```
https://www.sciencebase.gov/catalog/items?filter=spatialQuery={wkt:"POLYGON%20((-89%2045,-89%2046,-88%2046,-88%2045,-89%2045))",relation:"intersects"}&parentId=4f70ab22e4b058caae3f8deb&format=json&max=1000

if I get some time, I'll try to put this back in to ``usgs.ned``
