### ISSUE TITLE
nwis service is broken with usgs http --> https move

### ISSUE THREAD

**Issue by solomon-negusse** [ulmo-dev/ulmo#140]
here is the error with both iv/dv services:
```
Certificate did not match expected hostname: waterservices.usgs.gov. Certificate: {'notAfter': 'Mar  1 12:00:00 2017 GMT', 'subjectAltName': (('DNS', '*.er.usgs.gov'), ('DNS', 'er.usgs.gov')), 'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'Virginia'),), (('localityName', u'Reston'),), (('organizationName', u'U.S. Geological Survey'),), (('organizationalUnitName', u'USGS'),), (('commonName', u'*.er.usgs.gov'),))}
```
This is caused by a [known issue](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484) in requests library (technically urllib3) that affects Python < 2.7.9 and can be fixed by adding the dependencies (PyOpenSSL, ndg-httpsclient, pyasn1). I have tested that this works locally.  I'll submit a PR adding this in requirements file.

**Comment by dharhas** [comment]
sounds good.

**Comment by emiliom** [comment]
I also ran into this problem, and can confirm that @solomon-negusse's fix worked.

FYI, I didn't actually install ulmo using the updated `requirements.txt` file (though it looks totally fine). I had a need to avoid an ulmo reinstall if at all possible. In my case, I had a conda environment were `pyasn1` and `pyopenssl` were already installed; I just installed `ndg-httpsclient` on that environment, and it worked.

**Comment by dharhas** [comment]
pr's welcome. Also since this is only an issue for python < 2.7.9, it would be better to only specify those packages for python < 2.7.9.

**Comment by solomon-negusse** [comment]
I hit a couple of issues implementing this fix:
- httpretty mocking doesn't support https. I experimented mocking with [responses](https://github.com/getsentry/responses) which works for most cases but some tests were failing and didn't have time to follow thru.
- openssl install fails on windows (https://ci.appveyor.com/project/dharhas/ulmo/build/1.0.152/job/p2o3vh63rup23sio). I'm not sure what it'd take to fix this and it'll be a while before I can take a look.

I assumed you'd want tests to work on windows before merging so this got  stalled.  Once that's resolved, I can submit a pr for this with mocking disabled for https requests and open a different issue for mocking fix.

**Comment by emiliom** [comment]
I'll close this w/o addressing it. Python 2.7.9 is from Dec 2014 (5 years ago) -- not to mention the fact that 2.7 is only a few months away from EoL.
