### ISSUE TITLE
CPC Drought returns data for a week that hasn't been posted yet.

### ISSUE THREAD

**Issue by ajford** [ulmo-dev/ulmo#144]
This appears to be the result of a corner case where CPC's current data file hasn't been rotated for the new growing season. 

If you call `ulmo.cpc.drought.get_data()`, you get records for the current week (March 05-11 2017), when there is no such record. The data in that record is equivalent to the data for the same climate division for the week of March 06-12 2016. 

For future need/reference, this is the `current.data` file as of today (2017-03-08): [2017-03-08_current.data.txt](https://github.com/ulmo-dev/ulmo/files/828929/2017-03-08_current.data.txt)

I think I have found the cause. In [cpc.drought.core (L299)][drought.core], the year column from the data is replaced by the year specified in the call to [cpc.drought.core._parse_data_file][_parse_data_file]. This appears to be introduced by PR #87. 

This solution works for past data files (such as those referenced in PR #87). This however fails when the condition described in #87 exists in the `current.data` file. It appears that when the loop over year range occurs on [L136 of  `cpc.drought.core.get_data()`][get_data], it applies the current year (2017) to the year column of the current data, and shifts all dates by one year. The date range trimming occurs on [L161 of `cpc.drought.core.get_data()`][date_trim], but includes the current week. Since this data "exists" in the shifted data set, it gets included. 

A demo code is available [here](https://gist.github.com/ajford/2814e5a266c4e6e6129a7e89b4b27132).
This should run on any Py2.7 env with Ulmo installed. Sorry, didn't bother with Py3 compat. It shows that the latest records have a period that is not in the datafile, as well as showing that two records for a specific Climate Div (Texas CD 10) is identical for March 06-12 2016 and March 05-11 2017. 

[drought.core]: https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cpc/drought/core.py#L299
[_parse_data_file]: https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cpc/drought/core.py#L263
[get_data]: https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cpc/drought/core.py#L136
[date_trim]: https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cpc/drought/core.py#L161

**Comment by ajford** [comment]
Looking at it, I think there's two possible directions to take the fix.

One route is to special case the current data (since it's not strictly batched by year) and use the year column undisturbed. A quick and dirty test I did with just commenting out L299 works, though I didn't implement the special casing. 

The other route is to tighten the date range trimming on L161. If we assume that the weekly data can't/won't be released mid week (as in you can't have the data for Mar 05-11 2017 on Mar 8th 2017), then we can shorten the date range to the previous Saturday (end of the week according to CPC). This might get weird with data releases on Saturday (as in fetching the data on Saturday, will it be their?), but that corner case can be avoided.

Also, writing the test cases for this is going to be fun...

What do you think @dharhas?

**Comment by ajford** [comment]
After some thinking and some work in Jupyter, I ended up implementing the first option. It looks like using the data file year column on the current data works fine, and shouldn't affect the older data.

I'm going to run some tests and see if I can get some unit testing written for this.

**Comment by solomon-negusse** [comment]
Great, thanks for the update!
