### ISSUE TITLE
[GHCN Daily] Add an "all_elements = True" to the get_stations function

### ISSUE THREAD

**Issue by anirudhn18** [ulmo-dev/ulmo#151]
The `ncdc.ghcn_daily.get_stations` function returns those stations which contain data for ANY of the elements.

Could we include an option `all_elements` (`False` by default) to return stations which contain data  for ALL the elements provided?

**Comment by dharhas** [comment]
IF I remember the way GHCN website works its going to download all the data anyway, so this won't save you any download time. You can probably add a filter before returning the data to implement what you need. Pull requests are welcome.

**Comment by anirudhn18** [comment]
> You can probably add a filter before returning the data

The results of `get_stations` do not contain the available elements for that station so there's no real scope of applying the filter on that. I'm building a process that relies on having stations containing all desired elements.
Currently, I can achieve the same through creating 3 (say) unique station lists and then selecting the intersection in these lists. But I thought it would be neat if `get_stations` itself had this facility.

> Pull requests are welcome.
I can take a shot at implementing this and creating a pull request for the same. Since I have very limited formal programming experience, I can't promise a polished version by any means.

**Comment by dharhas** [comment]
I'm not sure there is any way of knowing what elements are available for a station without downloading the data and inspecting.

**Comment by emiliom** [comment]
Very old issue, closing.
