### ISSUE TITLE
[GHCN Daily] Station list input to get_data?

### ISSUE THREAD

**Issue by anirudhn18** [ulmo-dev/ulmo#152]
I was wondering if there was any reason why `ulmo.ncdc.ghcn_daily.get_data` can't take a list of `station_id` as input. The corresponding function for `ulmo.ncdc.gsod` takes a list of stations as input.

**Comment by dharhas** [comment]
I can't recall of the top of my head, but I think it was the fact that the data is organized by year on the server and not by station_id, so it takes the same amount of time to get one station as all of them. That said a convenience function could be added to filter the data down before returning it.

**Comment by emiliom** [comment]
Very old issue, closing.
