### ISSUE TITLE
Add suds-jurko timeout support in cuahsi/wof

### ISSUE THREAD

**Issue by rajadain** [ulmo-dev/ulmo#155]
Hello,

I'm a developer for https://github.com/WikiWatershed/model-my-watershed. While working with Ulmo, at times we've felt the need to specify a custom timeout (opposed to the default 90s). `suds-jurko` supports timeouts for both the [http](https://bitbucket.org/jurko/suds/src/94664ddd46a61d06862fa8fb6ba7b9e054214f57/suds/transport/http.py?at=default&fileviewer=file-view-default#http.py-49) and [https](https://bitbucket.org/jurko/suds/src/94664ddd46a61d06862fa8fb6ba7b9e054214f57/suds/transport/https.py?at=default&fileviewer=file-view-default#https.py-46) modules. It would be great if they could be surfaced in the Ulmo API, just as [caching currently is](https://github.com/ulmo-dev/ulmo/blob/ba6ee72d91057c43d356e901a9ce511e1be16684/ulmo/cuahsi/wof/core.py#L284-L292). 

Without it, we have to wrap it in a [timeout decorator](https://github.com/pnpnpn/timeout-decorator), which is fine for now, but limits us to single-threaded work, since it [cannot handle non-pickleable responses in multithreaded environments](https://github.com/pnpnpn/timeout-decorator#multithreading). This wrapping is extraneous since suds _does_ have timeout support, it's just hidden from use.

Thanks.

**Comment by emiliom** [comment]
Thanks @rajadain. To give more context and details: I've been working with @rajadain on the broader project that uses the ulmo `cuahsi/wof` reader. We'll probably submit a couple of commits in the near future addressing some issues, including the one @rajadain describes here.

**Comment by emiliom** [comment]
I suggest the title of this issue be renamed to "Add suds-jurko timeout support in cuahsi/wof". I don't have permission to change it.

**Comment by dharhas** [comment]
If y'all submit a pull request, ideally with a few tests, I can merge it in. I don't actively use the cuahsi/wof plugin.

**Comment by emiliom** [comment]
Addressed in PR #165. Closing.

**Comment by emiliom** [comment]
Ah. I forgot I didn't open this issue, so I can't close it! @dharhas, you can close this issue any time.
