### ISSUE TITLE
pandas timestamp to_datetime() method seems to be deprecated

### ISSUE THREAD

**Issue by alemood** [ulmo-dev/ulmo#156]
As of June 2018 with pandas 0.23.0.  This affects `util` and the [usgs.get_site_data](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/usgs/nwis/core.py#L171) when specifying time periods for retrieval.

pd.Timestamp('1999-1-1').date() does not appear to be equivalent to pd.to_datetime(pd.Timestamp('1999-1-1)). The  docstring states that [util.misc.convert_datetime()](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/util/misc.py#L48) needs to return a datetime.date object, so perhaps the .date() method is appropriate?

**Comment by emiliom** [comment]
Was addressed way back in https://github.com/ulmo-dev/ulmo/commit/676f29bfc0c161e196caa0054bdd550946dbfedc. But I'm running into a new inconsistency with the `period` argument in `test/usgs_nwis_test.py::test_get_site_data_single_site_with_period` that might be related to this. It has to do with the interpretation of 'P45D' in `usgs.nwis.get_site_data(site_code, period='P45D', service='daily')` and whether it returns 44 or 45 values. Need to investigate.

**Comment by emiliom** [comment]
The concern above (`period` argument) has gone away, so it wasn't related to this issue. So, I'm closing this issue, since it was already addressed.
