### ISSUE TITLE
Bug fix for NASA ORNL Daymet weather?

### ISSUE THREAD

**Issue by emiliom** [ulmo-dev/ulmo#166]
@talbertc-usgs Last November you made [this comment](https://github.com/ulmo-dev/ulmo/issues/161#issuecomment-441365337) on another issue:

> I just happened to have found a bug caused by a change in the service for NASA ORNL's Daymet. It's an easy fix. If Ulmo will be continuing I can submit a pr.

@dharhas is moving quickly on a new ulmo release that incorporates several bug fixes and small improvements. It'd be really great if you could submit a PR for the ORNL Daymet bug fix you mentioned, so it can be part of this new release!

I don't actually use Daymet, so I have nothing to contribute other than this housekeeping. BTW, the link to [Daymet on the ulmo docs](https://ulmo.readthedocs.io/en/latest/api.html#module-ulmo.nasa.daymet) is broken. Should it just point to the Daymet home page, https://daymet.ornl.gov ?

**Comment by dharhas** [comment]
I think I fixed the bug in 78094c441fd9c, at least the tests pass now. I did not fix the docs issue.

**Comment by emiliom** [comment]
Great!

**Comment by talbertc-usgs** [comment]
Hello Emilio,

Hopefully it's not too late.  I'll see if I can get a pr put together.

-- Colin

Colin Talbert
Data Manager, Analyst and Developer
US Geological Survey, Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425
http://orcid.org/0000-0002-9505-1876


Work schedule:
Monday, Thursday       -   7:00 - 5:00
Tuesday - Wednesday -   7:00 - 3:10
Friday (Telework)         -   7:00 - 5:00

**Comment by dharhas** [comment]
@talbertc-usgs have a look at the fix I made. It may not be the same one that you found.

**Comment by talbertc-usgs** [comment]
It looks like @Dharhas already put in a fix for this.  Thanks for your work
on this project.

Thanks,
Colin


Colin Talbert
Data Manager, Analyst and Developer
US Geological Survey, Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425
http://orcid.org/0000-0002-9505-1876


Work schedule:
Monday, Thursday       -   7:00 - 5:00
Tuesday - Wednesday -   7:00 - 3:10
Friday (Telework)         -   7:00 - 5:00

**Comment by emiliom** [comment]
Great! Closing this issue.
