### ISSUE TITLE
intake integration?

### ISSUE THREAD

**Issue by dazza-codes** [ulmo-dev/ulmo#167]
RE - https://github.com/ContinuumIO/intake

What are the options for integrating ulmo with intake?  (If possible.  If not already done?)

https://intake.readthedocs.io/en/latest/quickstart.html
https://intake.readthedocs.io/en/latest/making-plugins.html

**Comment by dharhas** [comment]
If I started ulmo today, it would be a layer on top of intake. We are developing another project called quest (https://github.com/erdc/quest) that has a lot of overlap with the functionality of ulmo but isn't really a replacement. Quest is currently being refactored to use intake for its IO layer.

Bottom line is it makes sense for ulmo to use intake but unless someone steps up to make it happen it won't. My day job has diverged from using ulmo enough that I'm just in maintenance mode, accepting bug fixes and pull requests.
