### ISSUE TITLE
CPC tests failing

### ISSUE THREAD

**Issue by emiliom** [ulmo-dev/ulmo#170]
2 of the 3 CPC tests are failing:` test/cpc_drought_test.py::test_get_data_by_state` and `test/cpc_drought_test.py::test_get_data`. It was mentioned elsewhere that this might be due to a change in test data or website.

Ignoring for now, to go ahead and issue new release.

Also there's an open CPC issue, #144, but it looks like a PR #145 fixed it. Check if the issue was addressed, then close it.

**Comment by solomon-negusse** [comment]
Hi @emiliom, the fix for #144 has been working for us so this should be good to close. [Tests](https://travis-ci.org/ulmo-dev/ulmo/builds/626442379) have been fixed with the new PR I just opened.

**Comment by emiliom** [comment]
Thanks so much, @solomon-negusse ! The http to https transition is still propagating
