### ISSUE TITLE
Updating readthedocs docs

### ISSUE THREAD

**Issue by emiliom** [ulmo-dev/ulmo#177]
@dharhas I'm working on updating ulmo's readthedocs sphinx docs at https://ulmo.readthedocs.io. They're not updating automatically. I'm guessing this was caused by the [shutting down of GitHub Services in January 2019?](https://docs.readthedocs.io/en/stable/webhooks.html#i-was-warned-i-shouldn-t-use-github-services) The docs didn't update when I issued a new release in March 2019.

I've never used readthedocs. From what I've read, I assume I need to have access to the account where it was set up; could you give me access, transfer access to me, or if I can make all the changes on my end, point me in the right direction?

I'm able to update ulmo Sphinx docs on my local clone, so I'm good to go on that end.

Thanks!

**Comment by dharhas** [comment]
@emiliom Please create an account on readthedocs and let me know what your username is and I can add you as a maintainer.

**Comment by emiliom** [comment]
My readthedocs username is `emiliom`. Thanks!

**Comment by emiliom** [comment]
@dharhas A reminder before it falls off your radar. Hopefully adding me (`emiliom`) as a maintainer won't take much of your time.

**Comment by dharhas** [comment]
Done.

**Comment by emiliom** [comment]
Awesome, thank you!

**Comment by emiliom** [comment]
Got readthedocs working again. It's now using a [.readthedocs.yml](https://github.com/ulmo-dev/ulmo/blob/master/.readthedocs.yml) file instead of the https://readthedocs.org web admin interface settings ("advanced settings").

**Comment by emiliom** [comment]
Add a readthedocs badge to the `README.rst` file, with this code fragment:

```rst
.. image:: https://readthedocs.org/projects/ulmo/badge/?version=latest
:target: https://ulmo.readthedocs.io/en/latest/?badge=latest
:alt: Documentation Status
```

See https://readthedocs.org/projects/ulmo/

**Comment by emiliom** [comment]
> Add a readthedocs badge to the README.rst file, with this code fragment:

This was added a while ago.

I've now set up a ReadTheDocs "activation rule" to activate a new package version based on a tagged release.
