### ISSUE TITLE
NASA GOES reader

### ISSUE THREAD

**Issue by emiliom** [ulmo-dev/ulmo#178]
Review and merge [NASA GOES reader PR](173) from @flynnpc. This new reader replaces the USGS EDDN reader, which is no longer functional (web service is inaccessible).

**Comment by emiliom** [comment]
Once the issue of the failing test is addressed (see comments at #173), I'll add header RST docstrings to `noaa/__init__.py`, `noaa/goes/__init__.py` and `noaa/goes/core.py`; to be adapted from the EDDN docstrings. I'll assume that the new NOAA GOES reader gets at exactly the same data as the EDDN reader and the replacements for the two EDDN links are https://dcs1.noaa.gov/ and https://dcs1.noaa.gov/LRGS/DCP-Data-Service-14.pdf

Then add a corresponding entry to `docs/api.rst` and check that the sphinx `autodoc` is working as expected.

Finally, remove all EDDN code, documentation and tests.

**Comment by emiliom** [comment]
PR #187 was indirectly related to this, but was withdrawn.

**Comment by solomon-negusse** [comment]
Hey @emiliom, Just FYI - we're not ready to push the updates in the withdrawn PR but we should finish up this PR soon.

**Comment by emiliom** [comment]
See this new PR, #199

**Comment by emiliom** [comment]
Alright, the test passed using the the new way to build a dev conda environment (which I'll document). Woo-hoo! I'm closing this issue.
