### ISSUE TITLE
suds-jurko and setuptools 58 conflict with pip install

### ISSUE THREAD

**Issue by emiliom** [ulmo-dev/ulmo#212]
From https://github.com/snowex-hackweek/docker-image/pull/29#issuecomment-926816539:

> running into an issue with ulmo dependency `suds-jurko` andersinno/suds-jurko#6 , workaround seems to be pinning `setuptools<58`

**Comment by KehanGit** [comment]
Any updates on this conflict? I am running into the same problem.

**Comment by emiliom** [comment]
From @KehanGit , from another exchange:

> I am trying to use it for the SNOTEL data analysis and installed in successfully but when I tried to import the package, it has an error as shown below.

![image](https://user-images.githubusercontent.com/742403/168495139-90f6dbb7-04a9-474c-bb3c-4dc18fa5fdae.png)

@KehanGit could you specify how you installed ulmo, what version of ulmo was installed, and what suds library (I assume it was suds-jurko) and version was installed?

For reference, #189 is somewhat related to this issue.

**Comment by emiliom** [comment]
I installed ulmo just now, like this:
```
mamba create -n ulmo_test -c conda-forge python==3.8 ulmo ipykernel
```

Then I was able to import ulmo without problems.

FYI, I'm on Ubuntu Linux; I pinned Python to 3.8 b/c that's what I see in your error report; I added `ipykernel` just to be able to test in IPython; and I used `mamba` rather than `conda` to get to a successful conda environment more quickly.

**Comment by KehanGit** [comment]
Hi Emilio,

Thanks a lot for your reply.
To install ulmo, I used 'pip install ulmo' on a python virtual environment
on Ubuntu Linux. I have installed ipykernel on this environment.

Do you have any idea what may cause the errors I had? Thanks!

Best regards,
Kehan

**Comment by emiliom** [comment]
Thanks for the information. I've created a conda environment where I then installed ulmo via `pip install ulmo`. I then ran into an error when trying to do `import ulmo`, though the error was different from yours.

What version of ulmo was installed? I don't remember how to find the version in an environment that's not conda, if import ulmo fails! Can someone in your group help you get at that? What I found with my test with pip install is that it ended up falling back to a really, really old version of ulmo, 0.5.0! The initial errors start during pip install while installing `suds-jurko`. It ends up failing to install `suds-jurko` altogether and instead installs its much older predecessor, `suds`.

Do you use conda? From what I can tell, that would solve the problem and let you use ulmo w/o problems.

**Comment by emiliom** [comment]
I went back and tried the recommendation at the start of this issue: pinning setuptools to <58 when installing ulmo via pip install. That worked! import ulmo no longer leads to an error.

**Comment by jayqi** [comment]
I've got a simple workaround for the setuptools + suds-jurko issue that folks may find helpful.

What I've done is pre-build a wheel (using the older version of setuptools) and made that available on GitHub: https://github.com/drivendataorg/suds-jurko-wheel

You can then either install the wheel distributed on that repository first or side-by-side with ulmo and it will install with no problems. 

For example:

```bash
pip install ulmo "suds-jurko @ https://github.com/drivendataorg/suds-jurko-wheel/releases/download/v0.6/suds_jurko-0.6-py3-none-any.whl"
```

or in a `requirements.txt`

```
suds-jurko @ https://github.com/drivendataorg/suds-jurko-wheel/releases/download/v0.6/suds_jurko-0.6-py3-none-any.whl
ulmo
```

The wheel is redistributing suds-jurko without modification. The build process happens in [GitHub CI](https://github.com/drivendataorg/suds-jurko-wheel/actions/runs/6738208618) transparently, and the build script is [here](https://github.com/drivendataorg/suds-jurko-wheel/blob/main/build.sh). 

This way you don't need to fuss with setuptools or don't need to be forced to use conda.

**Comment by emiliom** [comment]
Thank you @jayqi !! To make it simpler for future users who run into this problem, I'll close this issue and leave #215 open (it has a more unambiguous title than this one); that's the other issue where you commented on your solution.
