### ISSUE TITLE
"getting started" examples and tutorials

### ISSUE THREAD

**Issue by wilsaj** [ulmo-dev/ulmo#37]

**Comment by emiliom** [comment]
I was going to create a new issue, but discovered this one already open. [This email question and response](https://groups.google.com/d/msg/ulmo/j2krMCuFGKI/sAAjATp6BNwJ) from @dharhas makes me think that it'd be nice to have a page where "the community" could contribute links to examples. Dharhas pointed to two examples of his. I have a couple of IPython notebooks I'd be happy to link to, incuding these two (both referring to WaterOneFlow or CUAHSI HIS Central services):
- http://nbviewer.ipython.org/github/BiG-CZ/BiG-CZ-Toolbox/blob/master/ipynotebooks/2014OctMeeting/BiGCZ_Demo_4_ulmo_crbwofpy_vizer.ipynb
- http://nbviewer.ipython.org/github/BiG-CZ/BiG-CZ-Toolbox/blob/master/ipynotebooks/2014OctMeeting/BiGCZ_Demo_5_ulmo_cuahsi_HISCentralServices.ipynb

I'd be happy to clean them up a bit to make them more digestible and remove crud. 

If this examples page were a simple Markdown (or some other very simple format) file on github that anyone could issue a pull request on, that'd make it easier to contribute.

Just a thought.

**Comment by ColinTalbert** [comment]
I also think this is an idea worth incorporating into ulmo.  I think the use of notebooks is widespread and growing, and they uniquely provide a visually compelling demonstration of how to do something with a package.  Now that Github renders ipynb files it would be possible to create a curated list of example notebooks that demonstrates the capabilities of ulmo, and provides examples/tutorials for how to use it.  I would suggest that ulmo add a folder called "examples" at the same level as docs and test which contains these.  

I've created a pull request that has this folder and an example notebook showing an example of the daymet pixel data function that I wrote.  (https://github.com/ColinTalbert/ulmo/blob/AddExamples/examples/Using%20Daymet%20weather%20data%20from%20ORNL%20webservice.ipynb)  If that gets merged you could clean your notebooks up, add them to this folder and submit a pull request.

**Comment by emiliom** [comment]
I'd be happy to add a couple of notebooks to the collection. Could probably do it late this week, or by early next week. Specially if there's some traffic on this issue to serve as a reminder and inspiration (eg, if @dharhas accepts @ColinTalbert's PR). I have CUAHSI HIS and USGS NWIS notebooks.

**Comment by emiliom** [comment]
Very old. Closing
