### ISSUE TITLE
add a way to get usgs nwis parameter code names/descriptions

### ISSUE THREAD

**Issue by wilsaj** [ulmo-dev/ulmo#49]

**Comment by wilsaj** [comment]
available as a tab-separated file here: http://help.waterdata.usgs.gov/code/parameter_cd_query?fmt=rdb&group_cd=%

**Comment by dharhas** [comment]
I've written parsers for this as well as some other usgs metadata services as well as using threads to pull the entire USGS metadata catalog in about 10-15 seconds. They are in an internal USACE module. It's on my todo list to merge them into ulmo but it has been low on my priority.

**Comment by emiliom** [comment]
Very old, closing.
