### ISSUE TITLE
usgs.nwis.get_sites should use a different URL

### ISSUE THREAD

**Issue by timcera** [ulmo-dev/ulmo#62]
Currently the usgs.nwis.get_sites function uses:

http://waterservices.usgs.gov/nwis/dv/?sites=01646500&format=waterml
http://waterservices.usgs.gov/nwis/iv/?sites=01646500&format=waterml

Which doesn't have the site information that I need.

Instead, suggest this URL...
http://waterservices.usgs.gov/nwis/site/?format=rdb&sites=01646500

Which does have what I need.

If you want a bunch of info, this would even be better...
http://waterservices.usgs.gov/nwis/site/?format=rdb&sites=01646500&siteOutput=expanded

Kindest regards,
Tim

**Comment by emiliom** [comment]
Very old, closing.
