### ISSUE TITLE
support WaterML 2

### ISSUE THREAD

**Issue by jirikadlec2** [ulmo-dev/ulmo#77]
Hi,
It would be nice to support WaterML 2.0 in ulmo. WaterML 2 is a xml format for hydrologic data and it is an official standard of the OGC:
http://www.opengeospatial.org/standards/waterml

I think it's OK if only the getValues() method with an url parameter is supported.

An example WaterML 2.0 request is here:
http://data.fmi.fi/fmi-apikey/1cb8a6f3-d8f4-4ae7-8fc3-0b9449683cfb/wfs?request=getFeature&storedquery_id=fmi::observations::weather::timevaluepair&fmisid=101152&starttime=2013-08-01T00:00:00Z&endtime=2013-08-05T00:00:00Z&timestep=60&parameters=temperature

(this is a time-series of air temperature at a station in Finland)

I could try to help with the WaterML 2 support coding, but I'd need some help on where to put the new modules.

Regards,
Jiri Kadlec

**Comment by emiliom** [comment]
Very old, closing.
